### ISSUE TITLE
詳細タブについて

### ISSUE THREAD

**Issue by sakuramochi708** [ueckoken/KokenWiki#85]
kokenwikiの更新ありがとうございます。

いままで<summary></summary>で、表示を最小化したりオープンしたりできてたと思います。それがどうやら反映されてないみたいです。このままだと議事録も見れませんし、C言語講習も記事を大幅に改善しないといけないのでとても困惑しています。対応よろしくお願いします。

**Comment by sakuramochi708** [comment]
あれ、きえちゃった。＜summary＞＜/summary＞のことです。
ちなみに使用ブラウザはFirefoxです。

**Comment by otariidae** [comment]
unexpected degradation caused by #82

`customHTMLSanitizer` would fix this
https://nhn.github.io/tui.editor/2.3.0/ToastUIEditor

related code:
https://github.com/ueckoken/KokenWiki/blob/359da0d9b2b591e43ff04e407edf46584e7592f0/app/javascript/components/Markdown.js#L11-L14
https://github.com/ueckoken/KokenWiki/blob/359da0d9b2b591e43ff04e407edf46584e7592f0/app/javascript/components/MdEditor/Editor.js#L17-L30

**Comment by otariidae** [comment]
Reopen by #88

**Comment by otariidae** [comment]
Fixed.
Thanks for reporting the issue.
